services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - api/.env
    volumes:
      - ./api:/app
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html